name: Node CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: npm install

      - name: Lint 🧐
        run: npm run lint:check

      - name: Test 🚨
        run: npm test

      - name: Upload coverage to Codecov 🌂
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy 🏠
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/IHNA/IHNA_MessengerService/
            git pull
            npm install
            NODE_ENV=production pm2 restart Messenger  